In [1]:
import pandas as pd

In [38]:
df = pd.read_csv("../data/Online Retail.csv", encoding="ISO-8859-1")

In [39]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [4]:
# We can't assume the CustomerID.So, removing is only option.

In [6]:
df = pd.read_csv("../data/Online Retail.csv", encoding="ISO-8859-1")

In [40]:
df.duplicated().sum()

np.int64(5268)

In [9]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,01-12-2010 11:45,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,01-12-2010 11:45,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,01-12-2010 11:45,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,01-12-2010 11:45,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,01-12-2010 11:49,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,09-12-2011 11:34,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,09-12-2011 11:34,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,09-12-2011 11:34,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,09-12-2011 11:34,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,09-12-2011 11:34,2.08,14446.0,United Kingdom

In [21]:
d1 = df.duplicated(subset=["InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country"])

In [34]:
duplicates = df[df.duplicated(keep=False)]
duplicates.sort_values(by=list(df.columns)).head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,01-12-2010 11:45,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,01-12-2010 11:45,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,01-12-2010 11:45,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,01-12-2010 11:45,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,01-12-2010 11:45,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,01-12-2010 11:45,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,01-12-2010 11:45,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,01-12-2010 11:45,2.95,17908.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,01-12-2010 11:49,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,01-12-2010 11:49,1.65,17920.0,United Kingdom

In [35]:
for col in df.columns:
    print(col, df[col].duplicated().sum())

InvoiceNo 516009
StockCode 537839
Description 537685
Quantity 541187
InvoiceDate 518649
UnitPrice 540279
CustomerID 537536
Country 541871

In [36]:
df[df.duplicated()].shape

(5268, 8)

In [12]:
df.duplicated().sum()

np.int64(5268)

In [41]:
df.loc[df.duplicated(keep=False)].groupby(list(df.columns)).size()

InvoiceNo  StockCode  Description                          Quantity  InvoiceDate       UnitPrice  CustomerID  Country
536409     21866      UNION JACK FLAG LUGGAGE TAG           1        01-12-2010 11:45  1.25       17908.0     United Kingdom    2
           22111      SCOTTIE DOG HOT WATER BOTTLE          1        01-12-2010 11:45  4.95       17908.0     United Kingdom    2
           22866      HAND WARMER SCOTTY DOG DESIGN         1        01-12-2010 11:45  2.10       17908.0     United Kingdom    2
           22900       SET 2 TEA TOWELS I LOVE LONDON       1        01-12-2010 11:45  2.95       17908.0     United Kingdom    2
536412     21448      12 DAISY PEGS IN WOOD BOX             1        01-12-2010 11:49  1.65       17920.0     United Kingdom    2
                                                                                                                               ..
C572226    85066      CREAM SWEETHEART MINI CHEST          -1        21-10-2011 13:58  12.75      15321.0     United Kingdom    2
C574095    22326      ROUND SNACK BOXES SET OF4 WOODLAND   -1        03-11-2011 09:54  2.95       12674.0     France            2
C574510    22360      GLASS JAR ENGLISH CONFECTIONERY      -1        04-11-2011 13:25  2.95       15110.0     United Kingdom    2
C575940    23309      SET OF 60 I LOVE LONDON CAKE CASES   -24       13-11-2011 11:38  0.55       17838.0     United Kingdom    2
C580764    22667      RECIPE BOX RETROSPOT                 -12       06-12-2011 10:38  2.95       14562.0     United Kingdom    2
Length: 4837, dtype: int64